version: '2'
services:
    react_springboot-app:
        image: react_springboot
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://react_springboot-mysql:3306/react_springboot?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    react_springboot-mysql:
        extends:
            file: mysql.yml
            service: react_springboot-mysql
